SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS `projects` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `slug` VARCHAR(64) NOT NULL,
    `name` VARCHAR(128) NOT NULL,
    `country` VARCHAR(64) NOT NULL DEFAULT '',
    `flag_emoji` VARCHAR(16) NOT NULL DEFAULT '',
    `tagline` VARCHAR(255) NOT NULL DEFAULT '',
    `investment_amount` VARCHAR(64) NOT NULL DEFAULT '',
    `investment_value` DECIMAL(12,2) NULL,
    `investment_currency` CHAR(3) NOT NULL DEFAULT 'USD',
    `processing_period` VARCHAR(64) NOT NULL DEFAULT '',
    `target_crowd` VARCHAR(255) NOT NULL DEFAULT '',
    `overview_title` VARCHAR(255) NOT NULL DEFAULT '',
    `overview_text` TEXT,
    `policy_title` VARCHAR(255) NOT NULL DEFAULT '',
    `policy_text` TEXT,
    `costs_total` VARCHAR(128) NOT NULL DEFAULT '',
    `costs_note` VARCHAR(255) NOT NULL DEFAULT '',
    `cta_text` VARCHAR(128) NOT NULL DEFAULT '立即咨询',
    `hero_title` VARCHAR(255) NOT NULL DEFAULT '',
    `hero_desc` VARCHAR(512) NOT NULL DEFAULT '',
    `hero_gradient` VARCHAR(255) NOT NULL DEFAULT '',
    `sort_order` INT NOT NULL DEFAULT 0,
    `status` TINYINT NOT NULL DEFAULT 1,
    `deleted_at` DATETIME NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
